language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0

matrix:
    allow_failures:
        - php: 7.0

before_install:
    - sudo apt-add-repository --yes ppa:zoogie/sdl2-snapshots
    - sudo apt-get update

install:
   - sudo apt-get install libwebkitgtk-3.0-dev libgconf2-dev libghc-gstreamer-dev libsdl1.2-dev libgtk-3-dev

script: phpize && ./configure && make && make test

after_failure: cat wxWidgets-*/mybuild/config.log
